# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sdDisc <- function(x, n) {
    .Call(`_sdsfun_sdDisc`, x, n)
}

equalDisc <- function(x, n) {
    .Call(`_sdsfun_equalDisc`, x, n)
}

geometricDisc <- function(x, n) {
    .Call(`_sdsfun_geometricDisc`, x, n)
}

quantileDisc <- function(x, n) {
    .Call(`_sdsfun_quantileDisc`, x, n)
}

manualDisc <- function(x, breakpoint) {
    .Call(`_sdsfun_manualDisc`, x, breakpoint)
}

ArmaJenksBreaks <- function(inp_data, n_classes, is_sorted = FALSE) {
    .Call(`_sdsfun_ArmaJenksBreaks`, inp_data, n_classes, is_sorted)
}

naturalDisc <- function(x, n, sampleprob) {
    .Call(`_sdsfun_naturalDisc`, x, n, sampleprob)
}

DummyVar <- function(x) {
    .Call(`_sdsfun_DummyVar`, x)
}

DummyMat <- function(mat) {
    .Call(`_sdsfun_DummyMat`, mat)
}

CalcFactorQ <- function(y, h) {
    .Call(`_sdsfun_CalcFactorQ`, y, h)
}

GDFactorQ <- function(y, h) {
    .Call(`_sdsfun_GDFactorQ`, y, h)
}

MI_vec <- function(x, W, alternative = "greater", symmetrize = FALSE) {
    .Call(`_sdsfun_MI_vec`, x, W, alternative, symmetrize)
}

RcppHClustGeoMat <- function(D0, D1, alpha, scale = TRUE, wt_ = NULL) {
    .Call(`_sdsfun_RcppHClustGeoMat`, D0, D1, alpha, scale, wt_)
}

RcppJenksBreaks <- function(x, n_classes, is_sorted = FALSE) {
    .Call(`_sdsfun_RcppJenksBreaks`, x, n_classes, is_sorted)
}

LinearRegression <- function(y, X) {
    .Call(`_sdsfun_LinearRegression`, y, X)
}

LinearTrendRM <- function(y, X) {
    .Call(`_sdsfun_LinearTrendRM`, y, X)
}

PrintGlobalMoranI <- function(df) {
    .Call(`_sdsfun_PrintGlobalMoranI`, df)
}

RcppUnique <- function(x) {
    .Call(`_sdsfun_RcppUnique`, x)
}

CalcSPADEPSD <- function(y, h, wt) {
    .Call(`_sdsfun_CalcSPADEPSD`, y, h, wt)
}

RcppSpatialVariance <- function(x, wt) {
    .Call(`_sdsfun_RcppSpatialVariance`, x, wt)
}

Tbl2Mat <- function(coords, z_values) {
    .Call(`_sdsfun_Tbl2Mat`, coords, z_values)
}

