# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Runique <- function(x) {
    .Call(`_sdsfun_Runique`, x)
}

DummyVar <- function(x) {
    .Call(`_sdsfun_DummyVar`, x)
}

DummyMat <- function(mat) {
    .Call(`_sdsfun_DummyMat`, mat)
}

